#deployment e service num ficheiro

apiVersion: apps/v1
kind: Deployment                               #pra replicar dbs, usar StatefulSet
metadata:
  name: noti-api
  namespace: egs1          
  labels:
    app: noti-api
spec:
  replicas: 1                                 #n se deve replicar dbs
  selector:
    matchLabels:
      app: noti-api
  template:
    metadata:
      labels:
        app: noti-api
    spec:
      containers:
      - name: node-api
        image: registry.deti:5000/billsdivider/notificationsapi:29062022
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: noti-api
  namespace: egs1
spec:
  type: NodePort                                #external service type
  selector:
    app: noti-api                      #label dos pods pro service encontrar os pods
  ports:
    - protocol: TCP
      port: 3000                                #port of the service os requests vem praqui
      targetPort: 3000                          #o serviço redireciona para o port dos pods
      nodePort: 30100