#To run and build in NotificationsAPI dir: sudo docker-compose -f deploy/docker-compose.yml  up --build
#To run without build: sudo docker-compose -f deploy/docker-compose.yml  up

version: "3.3"
services:
  db:
    container_name: db
    image: mysql:8.0.21
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ../src/db/entry:/docker-entrypoint-initdb.d/:ro
      - ../src/db/data:/var/lib/mysql
    tty: true
  api:
    container_name: notification_api
    links:
      - db
    image: api
    build:
      context: ..
      dockerfile: deploy/Dockerfile.api
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
