FROM node

LABEL maintainer="Ana Ferreira"

LABEL version="1.0"

RUN apt update && apt install -y netcat

RUN mkdir /api

WORKDIR /api

COPY ./src ./

RUN npm install

EXPOSE 3000

RUN chmod +x startup.sh 

ENTRYPOINT ["./startup.sh"]
