apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-analu
  namespace: analu
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi