apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: noti-pvc-claim
  namespace: egs1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi